cleaning:
  drop_thresh: 0.8
  exclude_recontact_features: true
  fill_value: 0
clustering:
  method: kmeans
  n_clusters: 3
features:
  min_unique: 1
  use_variance_threshold: true
reduction:
  method: pca
  n_components: 2
storage:
  bucket: survey-dataset
  local_path: /tmp/dataset.xlsx
  object_name: dataset.xlsx
